### ISSUE TITLE
Deployment Question

### ISSUE THREAD

**Issue by rustanacexd** [kodless/leek#18]
What is a good way to deploy this?

**Comment by Stubatiger** [comment]
Well there are official docker containers for it, so thats a good way 
https://hub.docker.com/r/kodhive/leek

**Comment by rustanacexd** [comment]
Thank you.

**Comment by AdamiHamza** [comment]
@rustanacexd Leek can be deployed to any docker compatible cluster like ECS, EKS, K8S ...

You will find a terraform module at https://github.com/kodless/leek/tree/master/infra to deploy Leek into AWS ECS

If you don't want to use the managed AWS Elasticsearch you can add ES as a sidecar container since local ES container has been deprecated and removed from docker image to improve Leek docker image size and to encourage the use of a more manageable ES nodes.

The other reason for deprecating local ES is because we have noticed that ES starts throttling requests after receiving 1 million continuous events in a small period from Leek.

If you have any other questions about deployment or if you face any issues/difficulties, please feel free to ask in this thread. I will be happy to help.
