### ISSUE TITLE
Timeout if broker connection cannot be ensured

### ISSUE THREAD

**Issue by Stubatiger** [kodless/leek#44]
I have multiple subscriptions set via `LEEK_AGENT_SUBSCRIPTIONS` with varying `broker` urls inside them.
If a single broker cannot be connected to, for example if the hostname cannot be resolved, the agent process will hang/fail 
at this step
```
INFO:leek.agent.consumer:(main) Building consumer [Subscription=mars-prod, Prefetch=1000, Pool=2] ...
INFO:leek.agent.consumer:(main) Ensure connection to the broker <BROKER_URL>...
```

A error will be thrown, but from what i have noticed is that, the brokers from the other subscriptions will not be connected to, although they may be reachable

**Comment by Stubatiger** [comment]
I have experienced this with version 0.5.0.

Sadly i cannot give anymore logs/infos.

**Comment by kodless** [comment]
@Stubatiger this is intentional!

During bootstrap, the agent will not start If any subscription from the subscriptions list is not healthy.

https://github.com/kodless/leek/blob/master/app/leek/agent/agent.py#L32-L37

This is useful to know that the agent is working properly, If the error is omitted, when you go to Leek UI -> Agent tab, you will see the agent status as `RUNNING`. However, a subscription is not healthy.
