### ISSUE TITLE
Suporting lightweight datastorage

### ISSUE THREAD

**Issue by lowercase00** [kodless/leek#48]
Hi, been looking for a Flower alternative for a while, so thanks for this.

As much as this seems promising, the use of Elasticsearch makes it unusable for small projects (uses 850MB of RAM but normally needs something like 1-1,5 Gb to run).

I'm thinking it would be great to have support for Postgres with FullText Search, or maybe even a SQLite option (it has a Full Text Search extension if I'm not mistaken).

As much of the data is pretty much ephemeral, there could be a logic implemented to keep data for X amount of days, to improve performance and make it lightweight.

I would be happy to contribute if you think this could make sense.

Thanks!

**Comment by espoirMur** [comment]
+ one for this .. Even file search ..

**Comment by lowercase00** [comment]
@kodless any thoughts on this?
I would be happy to contribute here. I though of adding a setting like "DB_BACKEND", that could be set like "ElasticSearch", or others, and then slowly accepting other databases.  I would consider TinyDB, for small projects it would probably work perfectly. Having ES as a dependency unfortunately makes it impossible to use for small projects (which is my case at the moment, around ~10k / msgs / day).
Let me know what you think.
Cheers!

**Comment by kodless** [comment]
@lowercase00 @espoirMur 

Unfortunately, short/medium term there is no plan to support other storage/search backends.

**For these reasons:**

- Leek frontend is using Elasticsearch Query Domain Specific Language (DSL), so query filters are easily prepared by frontend and the backend is only proxying those queries to Elasticsearch. If we are going to use relational SQL databases we will have to implement the filters on the backend. 

- Relational databases are not optimized for search, they will take forever to search over 500 Million celery tasks whereas ES will take couple of seconds.

- Elasticsearch has a top-notch support for aggregations, Leek frontend is using ES aggregations for almost everything (attribute filters, metrics page, app dropdown, env dropdown, monitor page, queues page, issues page, control commands...). Everything!

So It's really very hard to build these features (Queries, Aggregations, Blazing Fast Search...) that ES is offering out of the box. Also it's very tedious, We're not going to reinvent the wheel and try to build something from scratch. It will take a lot of time to build and it will not be as perfect as ES.

**What you can do?**

- Instead of having a dedicated instance of Elasticsearch, you can run an Elasticsearch sidecar container along with Leek application container.

- You can try other inferior monitoring tools like Flower or Clearly. however, they are also not supporting SQL data stores, As a matter of fact, they don't support any kind of storage. they support backup/restore from RAM to disc. which is not reliable.

**Note:** Before the current Leek (Leek v2), there was another internal version of Leek (Leek v1). it was based on Clearly (I have built a frontend for Clearly just like what you are trying to do) and I was storing events in SQL database. I have built those filters, aggregations ... on the backend. However, it was a mess, very slow and not reliable.

To conclude, Elasticsearch is the best storage/search backend for Leek and I'm afraid to say that I'm 90% sure there will be no support for other backends.

And Leek is the best celery tasks monitoring tool as of now thanks to Elasticsearch. and to be honest, without Elasticsearch Leek wouldn't be a thing!

**Comment by lowercase00** [comment]
@kodless thank you so much for your answer and detailed explanation.

I totally understand your points, and indeed in your scale it's a no brainer indeed. I still imagine that having a SQL backend alternative could make sense. I imagine fairly rare to have this kind of volume (500 M) in a short period of time. As an idea for the future, if the queries in the frontend were "generic", this could translate to more flexibility for different backend solutions. Another option to increase accessibility would be to try Zinc / Sonic. Haven't tried those, but maybe.

Awesome, I indeed have been trying to find something for a while know, relying on Flower has been less than ideal so to say... I have been writing some stuff, but mostly frontend yet. Would you be willing to share some of that legacy code? 

Thanks mate!

**Comment by kodless** [comment]
@lowercase00 First time I hear about Zinc / Sonic, do they support something like Elasticsearch painless scripts for scripted upserts?

I forgot to mention that Leek relies on Elasticsearch painless scripts to merge tasks because celery events are not `time-series` data, For example the `name`, `queue` attributes are only sent with `task-sent` and `task-started` events and do not exist on other events like `task-succeeded` event. Therefore we need to `upsert` instead of `index`, the painless scripts are used to:

- Resolve conflicts and merge any event type with the current indexed task attributes.
- Ensure that indexed task has the correct state even with concurrent Leek workers.
- Events come unordered so the painless script makes sure to infer the order.

Task painless script: https://github.com/kodless/leek/blob/master/app/conf/painless/TaskMerge.groovy

I would like to support lightweight datastores but it's very difficult to refactor leek for this feature and I don't have much time to conduct the refactoring.

I agree very few projects will have this kind of volume. the current project I'm working on can reach 550 M events / 136 M tasks per month

<img width="1730" alt="Screen Shot 2022-03-23 at 04 31 27" src="https://user-images.githubusercontent.com/56397909/159620462-88845064-357d-4a12-9b99-e0186bf9611a.png">

Leek V1 was developed during my working hours for the project I'm working on, Leek V2 was developed during my free time. Although Leek V1 is deprecated but legally I can't publish it (they are totally a different code).

**Comment by lowercase00** [comment]
@kodless not sure really, I don't have much experience with ES apart from the basic stack (fluent > ES > kibana).
Thanks for the explanation, it makes sense and indeed makes things way more robust.

If you had an idea on implementation I could try to slowly contribute to make it possible, but I understand it's just too coupled at the moment.

Sure, I understand. If you ever get the authorization to publish the code (or even part of it) would be great, I still can't help to think there's a huge need for an alternative Celery monitoring tool that's more "one size fits all" like Flower style.
