### ISSUE TITLE
tryleek.com down

### ISSUE THREAD

**Issue by dejlek** [kodless/leek#61]
Seems like the website is down. Is this intentional?

**Comment by kodless** [comment]
@dejlek it's down because tryleek.com dns is managed by AWS Route53 and Leek AWS account is suspended because I didn't pay bills, will try to pay the past due bills and remove the suspension.

Seems like few developers financially supports the project here https://www.buymeacoffee.com/fennec

If this remains the same in the next months maybe I will decide to stop maintaining/contributing to the project and archive the Github repository.
